# Generated by Django 4.0.4 on 2022-04-14 14:24

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idNo', models.IntegerField(default=0)),
                ('bio', models.TextField(blank=True, max_length=254)),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('emailaddress', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Neighbourhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True, verbose_name='Neighbourhood Title')),
                ('description', models.TextField(blank=True, max_length=254, verbose_name='Description')),
                ('location', models.CharField(blank=True, max_length=150, null=True, verbose_name='Neighbourhood Location')),
                ('neighbourhood_logo', cloudinary.models.CloudinaryField(max_length=255, verbose_name='neighbourhood_logo')),
                ('health_department', models.CharField(blank=True, max_length=15, null=True, verbose_name='Health Department')),
                ('police_department', models.CharField(blank=True, max_length=15, null=True, verbose_name='Police Department')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('neighbourhood_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Neighbourhood Admin')),
            ],
            options={
                'verbose_name_plural': 'Neighbourhoods',
            },
        ),
    ]
