# Generated by Django 4.0.4 on 2022-04-17 15:03

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='neighbourhood',
            options={},
        ),
        migrations.RemoveField(
            model_name='neighbourhood',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='neighbourhood',
            name='health_department',
        ),
        migrations.RemoveField(
            model_name='neighbourhood',
            name='neighbourhood_admin',
        ),
        migrations.RemoveField(
            model_name='neighbourhood',
            name='neighbourhood_logo',
        ),
        migrations.RemoveField(
            model_name='neighbourhood',
            name='police_department',
        ),
        migrations.RemoveField(
            model_name='neighbourhood',
            name='title',
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hood', to='App.profile'),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='health_contact',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='hood_logo',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='hood_logo'),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='police_contact',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='neighbourhood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.neighbourhood'),
        ),
        migrations.AlterField(
            model_name='neighbourhood',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='neighbourhood',
            name='location',
            field=models.CharField(max_length=60),
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('description', models.TextField(blank=True)),
                ('neighbourhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business', to='App.neighbourhood')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='App.profile')),
            ],
        ),
    ]
